name: Welcome to CAML
url: https://caml.csail.mit.edu/
description: The Clinical and Applied Machine Learning Group.

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

include:
  - _static

collections:
  - people
  - alumni

# Used by fun gallery
imagesurl: "/images/"
thumbsurl: "/thumbnails/" 

plugins:
  - jekyll-paginate